<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae">

        <!--hip指髋关节-->
        <joint name="${name}_hip_joint" type="revolute">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} ${leg_offset_z}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} ${leg_offset_z}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} ${leg_offset_z}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} ${leg_offset_z}"/>
            </xacro:if>
            <parent link="base"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/> <!--导出的是-1，绕世界坐标系的-y轴转，因为urdf导出反的，注意-->
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_position_min}" upper="${hip_position_max}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_position_max}" upper="${-hip_position_min}"/>
            </xacro:if>            
        </joint>

        <joint name="${name}_hip_stator_fixed" type="fixed">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${hip_stator_offset_x} ${-hip_stator_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${hip_stator_offset_x} ${hip_stator_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-hip_stator_offset_x} ${-hip_stator_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-hip_stator_offset_x} ${hip_stator_offset_y} 0"/>
            </xacro:if>
            <parent link="${name}_hip"/>
            <child link="${name}_hip_stator"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </joint>

        <link name="${name}_hip">
            <visual> <!--注意：这里link的原点手敲的，如果重新导出记得改-->
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                    <geometry>
                        <mesh filename="package://bitter/meshes/FL_hip_link.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                    <geometry>
                        <mesh filename="package://bitter/meshes/FR_hip_link.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                    <geometry>
                        <mesh filename="package://bitter/meshes/RL_hip_link.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                    <geometry>
                        <mesh filename="package://bitter/meshes/RR_hip_link.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                
            </visual>
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="${hip_offset_x*front_hind} ${hip_offset_y*mirror} 0"/>
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                    iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                    izz="${hip_izz}"/>       
            </inertial>
        </link>

        <link name="${name}_hip_stator">
                <!--不需要视觉，只要碰撞，5.21加的-->
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.15" radius="0.05"/>
                </geometry>
            </collision>
        </link>

        <!--thigh指大腿-->
        <joint name="${name}_thigh_joint" type="revolute">
            <origin rpy="0 0 0" xyz="${thigh_joint_offset_x*front_hind} ${thigh_joint_offset_y*mirror} 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_thigh"/>
            <axis xyz="0 -1 0"/> 
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_position_min}" upper="${thigh_position_max}"/>
        </joint>


        <link name="${name}_thigh">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}"> <!--左边-->
                        <mesh filename="package://bitter/meshes/FL_thigh_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}"><!--右边-->
                        <mesh filename="package://bitter/meshes/FR_thigh_link.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
            </visual>
            <collision> <!--将碰撞几何体的原点设置在大腿长度的中间位置,叉掉，看不懂自己之前写什么了-->
                <origin rpy="0 ${PI/2.0} 0" xyz="0 ${thigh_offset_y*mirror} ${-thigh_length-0.01}"/>
                <geometry>
                    <box size="${thigh_length} ${thigh_width} ${thigh_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                    ixx="${thigh_ixx}" ixy="${thigh_ixy*mirror}" ixz="${thigh_ixz}"
                    iyy="${thigh_iyy}" iyz="${thigh_iyz*mirror}"
                    izz="${thigh_izz}"/>       
            </inertial>
        </link>


        <!--calf指小腿-->
        <joint name="${name}_calf_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 ${calf_joint_offset_y*mirror} ${calf_joint_offset_z}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <axis xyz="0 -1 0"/> <!--这个和导出的一样1,但是不满足逆时针为正，改为-1-->
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${front_hind_dae == True}">
                <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_position_min}" upper="${calf_position_max}"/>
            </xacro:if>
            <xacro:if value="${front_hind_dae == False}">
                <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${-calf_position_max}" upper="${-calf_position_min}"/>
            </xacro:if>
        </joint>


        <link name="${name}_calf">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}"> <!--左边-->
                        <mesh filename="package://bitter/meshes/FL_calf_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}"><!--右边-->
                        <mesh filename="package://bitter/meshes/FR_calf_link.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 ${calf_offset_y*mirror} ${-calf_length/2.0}"/>
                <geometry>
                    <box size="${calf_length} ${calf_width} ${calf_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y*mirror} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                    ixx="${calf_ixx}" ixy="${calf_ixy*mirror}" ixz="${calf_ixz}"
                    iyy="${calf_iyy}" iyz="${calf_iyz*mirror}"
                    izz="${calf_izz}"/>       
            </inertial>
        </link>

        <!--foot指轮胎-->
        <joint name="${name}_foot_joint" type="continuous">
            <origin rpy="0 0 0" xyz="0 ${foot_joint_offset_y*mirror} ${foot_joint_offset_z}"/>
            <parent link="${name}_calf"/>
            <child link="${name}_foot"/>
            <axis xyz="0 -1 0"/> <!---->
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${foot_torque_max}" velocity="${foot_velocity_max}" />
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}"> <!--左边-->
                        <mesh filename="package://bitter/meshes/FL_wheel_link.STL" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}"><!--右边-->
                        <mesh filename="package://bitter/meshes/FR_wheel_link.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
            </visual>
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 ${foot_offset*mirror} 0"/>
                <geometry>
                    <cylinder length="${foot_length}" radius="${foot_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${foot_com_x} ${foot_com_y*mirror} ${foot_com_z}"/>
                <mass value="${foot_mass}"/>
                <inertia
                    ixx="${foot_ixx}" ixy="${foot_ixy*mirror}" ixz="${foot_ixz}"
                    iyy="${foot_iyy}" iyz="${foot_iyz*mirror}"
                    izz="${foot_izz}"/>       
            </inertial>
        </link>

    </xacro:macro>
</robot>
