(cl:defpackage robot_msgs-msg
  (:use )
  (:export
   "<BITTERIMU>"
   "BITTERIMU"
   "<IMU>"
   "IMU"
   "<LOWLEVELCMD>"
   "LOWLEVELCMD"
   "<LOWLEVELMOTORCMD>"
   "LOWLEVELMOTORCMD"
   "<LOWLEVELMOTORSTATE>"
   "LOWLEVELMOTORSTATE"
   "<LOWLEVELSTATE>"
   "LOWLEVELSTATE"
   "<MOTORCOMMAND>"
   "MOTORCOMMAND"
   "<MOTORSTATE>"
   "MOTORSTATE"
   "<OBSERVATION>"
   "OBSERVATION"
   "<ROBOTCOMMAND>"
   "ROBOTCOMMAND"
   "<ROBOTSTATE>"
   "ROBOTSTATE"
  ))

