w1/robot_lab:
  model_name: "policy_0926_3.pt"
  framework: "isaacsim"
  dt: 0.005
  decimation: 4
  num_observations: 57 
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [] # 0 is the latest observation zyl
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0,  # 添加 .0 转为浮点型
                       -100.0, -100.0, -100.0, -100.0,
                       -100.0,-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0,      # 添加 .0 转为浮点型
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [40.0, 40.0, 40.0, 0.0,
          40.0, 40.0, 40.0, 0.0,
          40.0, 40.0, 40.0, 0.0,
          40.0, 40.0, 40.0, 0.0]
  rl_kd: [0.5, 0.5, 0.5, 0.5,
          0.5, 0.5, 0.5, 0.5,
          0.5, 0.5, 0.5, 0.5,
          0.5, 0.5, 0.5, 0.5] 
  fixed_kp: [600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0]
  fixed_kd: [4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5]
  num_of_dofs: 16
  action_scale: [0.5, 0.5, 0.5, 5.0, 
                 0.5, 0.5, 0.5, 5.0, 
                 0.5, 0.5, 0.5, 5.0, 
                 0.5, 0.5, 0.5, 5.0 ]

  wheel_indices: [3, 7, 11, 15]
  leg_indices: [0, 1, 2,
                4, 5, 6,
                8, 9, 10,
                12, 13, 14]

  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0] #zyl
  gravity_vec_scale: 0.5

  torque_limits: [80.0, 80.0, 80.0, 80.0,
                  80.0, 80.0, 80.0, 80.0,
                  80.0, 80.0, 80.0, 80.0,
                  80.0, 80.0, 80.0, 80.0]

  default_dof_pos: [0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0]
  
  # 发布命令和接受电机状态的关节顺序
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller", "FL_foot_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller", "FR_foot_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller", "RL_foot_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller", "RR_foot_controller"]

  action_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller", "FL_foot_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller", "FR_foot_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller", "RL_foot_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller", "RR_foot_controller"]
