# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/BitterImu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class BitterImu(genpy.Message):
  _md5sum = "0f4e8b4bfb725baef44f23478818d1c0"
  _type = "robot_msgs/BitterImu"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# 自定义IMU消息格式
Header header # ROS标准消息头

# 四元数姿态 (x, y, z, w)
float64[4] quat

# 角速度 (单位: rad/s)
float64[3] angular_vel_local

# 线性加速度 (单位: m/s²)
float64[3] linear_acc_local

# 协方差矩阵 (3x3, 按行优先展开)
float64[9] orientation_cov # 姿态协方差
float64[9] angular_vel_cov # 角速度协方差
float64[9] linear_acc_cov # 加速度协方差
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','quat','angular_vel_local','linear_acc_local','orientation_cov','angular_vel_cov','linear_acc_cov']
  _slot_types = ['std_msgs/Header','float64[4]','float64[3]','float64[3]','float64[9]','float64[9]','float64[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,quat,angular_vel_local,linear_acc_local,orientation_cov,angular_vel_cov,linear_acc_cov

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BitterImu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.quat is None:
        self.quat = [0.] * 4
      if self.angular_vel_local is None:
        self.angular_vel_local = [0.] * 3
      if self.linear_acc_local is None:
        self.linear_acc_local = [0.] * 3
      if self.orientation_cov is None:
        self.orientation_cov = [0.] * 9
      if self.angular_vel_cov is None:
        self.angular_vel_cov = [0.] * 9
      if self.linear_acc_cov is None:
        self.linear_acc_cov = [0.] * 9
    else:
      self.header = std_msgs.msg.Header()
      self.quat = [0.] * 4
      self.angular_vel_local = [0.] * 3
      self.linear_acc_local = [0.] * 3
      self.orientation_cov = [0.] * 9
      self.angular_vel_cov = [0.] * 9
      self.linear_acc_cov = [0.] * 9

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_4d().pack(*self.quat))
      buff.write(_get_struct_3d().pack(*self.angular_vel_local))
      buff.write(_get_struct_3d().pack(*self.linear_acc_local))
      buff.write(_get_struct_9d().pack(*self.orientation_cov))
      buff.write(_get_struct_9d().pack(*self.angular_vel_cov))
      buff.write(_get_struct_9d().pack(*self.linear_acc_cov))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 32
      self.quat = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 24
      self.angular_vel_local = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.linear_acc_local = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 72
      self.orientation_cov = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 72
      self.angular_vel_cov = _get_struct_9d().unpack(str[start:end])
      start = end
      end += 72
      self.linear_acc_cov = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.quat.tostring())
      buff.write(self.angular_vel_local.tostring())
      buff.write(self.linear_acc_local.tostring())
      buff.write(self.orientation_cov.tostring())
      buff.write(self.angular_vel_cov.tostring())
      buff.write(self.linear_acc_cov.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 32
      self.quat = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      start = end
      end += 24
      self.angular_vel_local = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.linear_acc_local = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 72
      self.orientation_cov = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 72
      self.angular_vel_cov = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      start = end
      end += 72
      self.linear_acc_cov = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
