// Generated by gencpp from file robot_msgs/LowlevelMotorCmd.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_LOWLEVELMOTORCMD_H
#define ROBOT_MSGS_MESSAGE_LOWLEVELMOTORCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct LowlevelMotorCmd_
{
  typedef LowlevelMotorCmd_<ContainerAllocator> Type;

  LowlevelMotorCmd_()
    : id(0)
    , q(0.0)
    , dq(0.0)
    , tau(0.0)
    , Kp(0.0)
    , Kd(0.0)
    , Kvp(0.0)
    , Kvi(0.0)  {
    }
  LowlevelMotorCmd_(const ContainerAllocator& _alloc)
    : id(0)
    , q(0.0)
    , dq(0.0)
    , tau(0.0)
    , Kp(0.0)
    , Kd(0.0)
    , Kvp(0.0)
    , Kvi(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _q_type;
  _q_type q;

   typedef float _dq_type;
  _dq_type dq;

   typedef float _tau_type;
  _tau_type tau;

   typedef float _Kp_type;
  _Kp_type Kp;

   typedef float _Kd_type;
  _Kd_type Kd;

   typedef float _Kvp_type;
  _Kvp_type Kvp;

   typedef float _Kvi_type;
  _Kvi_type Kvi;





  typedef boost::shared_ptr< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LowlevelMotorCmd_

typedef ::robot_msgs::LowlevelMotorCmd_<std::allocator<void> > LowlevelMotorCmd;

typedef boost::shared_ptr< ::robot_msgs::LowlevelMotorCmd > LowlevelMotorCmdPtr;
typedef boost::shared_ptr< ::robot_msgs::LowlevelMotorCmd const> LowlevelMotorCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator1> & lhs, const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.q == rhs.q &&
    lhs.dq == rhs.dq &&
    lhs.tau == rhs.tau &&
    lhs.Kp == rhs.Kp &&
    lhs.Kd == rhs.Kd &&
    lhs.Kvp == rhs.Kvp &&
    lhs.Kvi == rhs.Kvi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator1> & lhs, const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "287e30467db2eeba6fc4bc80506a1206";
  }

  static const char* value(const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x287e30467db2eebaULL;
  static const uint64_t static_value2 = 0x6fc4bc80506a1206ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/LowlevelMotorCmd";
  }

  static const char* value(const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# uint8 mode           # motor target mode\n"
"# float32 q            # motor target position\n"
"# float32 dq           # motor target velocity\n"
"# float32 tau          # motor target torque\n"
"# float32 Kp           # motor spring stiffness coefficient\n"
"# float32 Kd           # motor damper coefficient\n"
"# uint32[3] reserve    # motor target torque\n"
"\n"
"# uint8 mode           # 电机当前模式\n"
"uint8 id                # 电机ID\n"
"float32 q            # 电机当前位置（弧度）\n"
"float32 dq           # 电机当前速度（弧度/秒）\n"
"float32 tau          # 当前输出扭矩（牛·米）\n"
"#Kp ，Kd，反转参数reverse\n"
"float32 Kp\n"
"float32 Kd\n"
"float32 Kvp\n"
"float32 Kvi\n"
"#uint8 rv #反转参数\n"
"# int8 temperature     # 电机温度（由于温度传导缓慢，存在滞后现象）\n"
;
  }

  static const char* value(const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.q);
      stream.next(m.dq);
      stream.next(m.tau);
      stream.next(m.Kp);
      stream.next(m.Kd);
      stream.next(m.Kvp);
      stream.next(m.Kvi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LowlevelMotorCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::LowlevelMotorCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q: ";
    Printer<float>::stream(s, indent + "  ", v.q);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dq: ";
    Printer<float>::stream(s, indent + "  ", v.dq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tau: ";
    Printer<float>::stream(s, indent + "  ", v.tau);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Kp: ";
    Printer<float>::stream(s, indent + "  ", v.Kp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Kd: ";
    Printer<float>::stream(s, indent + "  ", v.Kd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Kvp: ";
    Printer<float>::stream(s, indent + "  ", v.Kvp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Kvi: ";
    Printer<float>::stream(s, indent + "  ", v.Kvi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_LOWLEVELMOTORCMD_H
