# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

w1:
  dt: 0.005
  decimation: 4

  fixed_kp: [600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0,
             600.0, 600.0, 600.0, 0.0]
  fixed_kd: [4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5,
             4.5, 4.5, 4.5, 4.5]

  num_of_dofs: 16
  wheel_indices: [3, 7, 11, 15]
  leg_indices: [0, 1, 2,
                4, 5, 6,
                8, 9, 10,
                12, 13, 14]

  torque_limits: [70.0, 80.0, 80.0, 80.0,
                  70.0, 80.0, 80.0, 80.0,
                  70.0, 80.0, 80.0, 80.0,
                  70.0, 80.0, 80.0, 80.0]


  default_dof_pos: [0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0,
                    0.0, -0.6, 0.6, 0.0]

  # default_dof_pos: [0.0, -0.74, 0.8, 0.0,
  #                   0.0, -0.74, 0.8, 0.0,
  #                   0.0, -0.74, 0.8, 0.0,
  #                   0.0, -0.74, 0.8, 0.0]

  # 发布命令和接受电机状态的关节顺序
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller", "FL_foot_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller", "FR_foot_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller", "RL_foot_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller", "RR_foot_controller"]
  
  # 强化学习网络输出的action的关节顺序
  action_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller", 
                            "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller", 
                            "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller", 
                            "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                            "FL_foot_controller", "FR_foot_controller", "RL_foot_controller", "RR_foot_controller"]
  